// @ts-check
// One autogenerated sidebar shared by all three docs instances (users/admins/it).
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  defaultSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
